### PR TITLE
Remove REDUCER_KEY

### LINKED ISSUE #221: remove REDUCER_KEY references
replace with state.app...

### PR DESCRIPTION
**Pull request by dartharaknus**
fixes #221

### CODE REVIEW

**Comment by howardchung** [comment]
You can tag the issue in the OP to auto close it when the PR is merged :)  I did it for you on this one

**Comment by dartharaknus** [comment]
> You can tag the issue in the OP to auto close it when the PR is merged

I don't understand what you mean.

**Comment by howardchung** [comment]
If your message starts with fixes and an issue, it'll associate them

**Comment by dartharaknus** [comment]
This is somehow broken. I don't know why.

**Pull request merged**
