### PR TITLE
fixes issue #309

### PR DESCRIPTION
**Pull request by mike-robertson**
I wouldn't mind getting input from @blukai, I chose colors that would be easy to read.

hover state:

### CODE REVIEW

**Comment by blukai** [comment]
Probably Material-ui [Grid List](http://www.material-ui.com/#/components/grid-list) can be better here?

**Comment by mike-robertson** [comment]
Idk, I was just fixing what was listed in the issue (text contrast). If you want to explore using the material ui component I think it's worth looking into. I do sort of like the current aesthetic more than the 'photo album' aesthetic of the material-ui component.

**Comment by mike-robertson** [comment]
@blukai you can just push those changes to this branch, assuming the changes you asked for are with the heroes page

**Comment by blukai** [comment]
image

**Pull request merged**
