### PR TITLE
Fixes issue/325: Update inflictorWithValue CSS

### LINKED ISSUE #325: match page fixes
- [ ] "Building map" should be capitalized
- [ ] ~~slightly smaller inflictorwithvalue~~
- [x] teamfights inflictorwithvalue shows index instead of number of uses

### PR DESCRIPTION
**Pull request by pvskarthikeya**
fixes #325 

Hi @howardchung. 
I made the following changes for issue (#325): 
- Updated the Buildings Map Text.
- Modified inflictorWithValue CSS.

### CODE REVIEW

**Comment by blukai** [comment]
> Modified inflictorWithValue CSS.

@howardchung, why we need to make smaller inflictorWithValue? All images in tables should have same height. I belive this change is wrong.

**Comment by howardchung** [comment]
IMO the image is a little big

**Comment by blukai** [comment]
They are not to big and not to small, looks perfect with text and, subtext and overlay. I was even thinking to make them a bit bigger (no more), golden mean hehe.

**Comment by howardchung** [comment]
OK.  In that case @pvskarthikeya please revert the change to inflictorWithValue and leave just the string change.

**Comment by howardchung** [comment]
Sync master to fix the diff

**Comment by pvskarthikeya** [comment]
@howardchung  I am in sync with the master. Is there something i am missing here?

**Comment by howardchung** [comment]
Is the change to palette intended?

**Comment by blukai** [comment]
@pvskarthikeya `inflictorWithValue` css has been moved into components/Visualizations/inflictorWithValue.css

**Comment by pvskarthikeya** [comment]
@blukai @howardchung Sorry Guys. Just saw that. Thank you for noticing that.

**Pull request merged**
