### PR TITLE
Update MatchStory (a la Reddit)

### PR DESCRIPTION
**Pull request by stevenchung**
Context: https://www.reddit.com/r/DotA2/comments/6ya3k6/detail/

Quick inline fixed for corner case

### CODE REVIEW

**Comment by gu3st** [comment]
TBH for meme status I prefer "asked"... but that's just me.

I'm also a fan of the codegolfing I applied to it :D 

`said_verb: this.message.substr(-1,1) === '?' && strings.story_chat_asked || strings.story_chat_said`

**Comment by howardchung** [comment]
I personally think "?" is a valid question (if a minimal one) so I think "asked" is correct.

The Reddit thread does mention a few other things though, like:
* Handling "?!", or some other strings with question marks not as the last character
* Adding additional terms such as "exclaimed" for an all caps message

@drusepth @mdiller for input

**Comment by drusepth** [comment]
Honestly, I actually prefer "asked" on just "?", but not with a super-strong preference. I read it as a question in my head.

I have no idea whether "!?" or "?!" should result in "asked" or "said", though. "Exclaimed" would probably be good here, as well as on all-caps messages and/or messages ending in "!".

**Comment by howardchung** [comment]
I think this is superseded by #1156

**Pull request closed without merging**
