### PR TITLE
Records page

### LINKED ISSUE #895: monthly records page
https://github.com/odota/core/pull/1439 adds support for showing the top matches in a bunch of fields.

Create a page showing these records

### LINKED ISSUE #899: sort search results by last match time (and display it)
Added this data in https://github.com/odota/core/pull/1441

Should make search results more useful

### PR DESCRIPTION
**Pull request by howardchung**
fixes #895 
fixes #899 

@blukai the hero text seems to be slightly vertically misaligned--any idea what's causing that?

### CODE REVIEW

**Comment by blukai** [comment]
`span`  with className `styles.iconBox` causes the problem

**Comment by howardchung** [comment]
Thanks, removed it and it looks fine now.  Do you remember what it was used for?

**Comment by blukai** [comment]
I guess it's for randomed, pred. victory, etc icons. Probably removing it can break some things, so look at some dota matches, that contains some of those to be sure that everything is fine

**Comment by howardchung** [comment]
Yeah you're right the icons are too close together without that class.  @mdiller can we just apply margin styles on the icons to space them?

**Comment by mdiller** [comment]
Whoops. Fixed it.

**Pull request merged**
