### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by albertcui**
Enjoy!

### CODE REVIEW

**Comment by howardchung** [comment]
@albertcui this is sending an insane number of emails.  Can you squash the commits and merge all in one or only open a PR when you're ready to merge?

**Comment by howardchung** [comment]
this is conflicting now after #606

**Comment by dartharaknus** [comment]
@mike-robertson What to do about this PR? You have already incorporated it, right?

**Comment by howardchung** [comment]
It needs to be synced with master since there are conflicts.  Also new translations will keep coming in

**Pull request merged**
