### PR TITLE
More info into table for small screen

### PR DESCRIPTION
**Pull request by vovastradamus**

### CODE REVIEW

**Comment by howardchung** [comment]
Do you have a screenshot showing the difference?

**Comment by vovastradamus** [comment]
image
image
expand table to width screen

**Comment by howardchung** [comment]
@blukai @dartharaknus opinions on this?  I'm not sure how I like how it looks with no border.  The more correct fix is to tab the table in mobile view or something.

**Comment by howardchung** [comment]
OK, let's give it a try

**Pull request merged**
