### PR TITLE
Fix broken hero images for firefox

### LINKED ISSUE #802: Misaligned first column side lines on tables
- OS: Arch Linux
- Screen Resolution: 2K, FHD
- Browser/Version: Mozilla Firefox 52.0

The coloured bar and 'party lines' on first table column are misaligned on following table views:
- overview
- matches
- match/overview
- match/benchmark
- match/combat
- match/farm
- match/objectives
- match/actions
- match/analysis
- match/log
- match/chat

Screenshots:

image

image

### PR DESCRIPTION
**Pull request by masad-frost**
fixes #802 

Was such a pain in the ass to debug, sometimes it magically fixes it self, also, making any changes to the style in the devtools fixes it, even if I changed the opacity or something.

I tested on IE, Chrome, and FF seems to be working.

### CODE REVIEW

**Comment by masad-frost** [comment]
Tests are broken? 😕

**Comment by howardchung** [comment]
stylelint complaining:
```
src/components/Visualizations/Table/HeroImage.css
 40:22  ✖  Expected newline after     declaration-block-semicolon-newline-after
           ";" in a multi-line                                                 
           declaration block                                                   
 40:22  ✖  Unexpected extra           no-extra-semicolons                      
           semicolon
```

**Comment by howardchung** [comment]
any update?

**Comment by masad-frost** [comment]
My bad, thought I had already fixed it.

**Pull request merged**
