### PR TITLE
Started on Items UI

### PR DESCRIPTION
**Pull request by dartharaknus**
Need to wait for items endpoint.

### CODE REVIEW

**Comment by howardchung** [comment]
Not sure if items will make it into MVP, because I want to change how the data is presented.  We can keep this open until we have an idea of what we want to do.

**Comment by howardchung** [comment]
@nicholashh how can it work for you when the server side API isn't implemented? :P

**Comment by dartharaknus** [comment]
LOL. @howardchung Can we have a simple server side API implemented which just lists 0 items for now. We can improve on that once this PR is merged.

**Comment by howardchung** [comment]
thats probably equivalent to just making the action return `[]` instead of actually making the http call.

**Comment by dartharaknus** [comment]
Hmm.. I think I will do that.

**Comment by dartharaknus** [comment]
Items return `[]` for now.

**Pull request merged**
