### PR TITLE
Fix HTTP-request to HTTPS

### PR DESCRIPTION
**Pull request by roman-kosov**
Cosmetics page was allowed to display insecure content from cdn.dota2.com
**Issue**: https://github.com/odota/ui/issues/436

### CODE REVIEW

**Comment by blukai** [comment]
There is an open issue https://github.com/odota/core/issues/1309. Doing it like this is wrong.

**Comment by roman-kosov** [comment]
@blukai thanks you for answer. I understood, @howardchung plans to use "cosmetics images" without cdn.dota2.com?

**Comment by blukai** [comment]
Almost but not 😆 https://github.com/odota/core/blob/master/svc/web.js#L59
The same should be for cosmetics.

**Comment by howardchung** [comment]
Yeah unfortunately it's not quite that straightforward since the Valve CDN has an invalid HTTPS cert.  We need to set up proxying through the core and then point to it.  We can keep this PR open for the eventual fix, though.

**Comment by dartharaknus** [comment]
Agree that this is a wrong implementation. Closing this PR.

**Pull request closed without merging**
