### PR TITLE
adds proptypes to some components

### PR DESCRIPTION
**Pull request by howardchung**
Questions:
* We seem to have several different ways of referencing the react proptypes.  Is one recommended?  I mostly used `React.PropTypes.string` but that's kind of scary because if I mistype `React.proptypes.string`, the lint will pass but the component will crash on run when it tries to access a nested nonexistent property.

### CODE REVIEW

**Comment by covertPZ** [comment]
I think we should be fine to do it with the `React.PropTypes.string`. If the variable is referenced incorrectly and the component crashes that should be pretty obvious before the push and even if it does get pushed it should be a quick fix. There's other reasons a component could crash that the lint wouldn't pick up so I don't think we should be too worried with that as a reason.

**Comment by gu3st** [comment]
Why not add the proptypes/defaultProps as a static get method on the class?    It's equivalent, but then it's encapsulated in the class itself.

**Comment by howardchung** [comment]
@gu3st example?

**Comment by gu3st** [comment]
Inside the class, you should be able to do something like this:

`
    static get propTypes(){ 
        return { <prop type object contents here> }
    }
`

It's defining a static (bound to class, not instance) getter method for propTypes, which accomplishes the same as ClassName.propTypes

It's worth trying out, I find it makes my classes nicer, without having propTypes/defaultProps just kinda.. hanging out outside of my Class

**Comment by howardchung** [comment]
I just followed the existing convention, not sure if @mike-robertson had a reason for doing it this way.

**Comment by howardchung** [comment]
React has moved proptypes to a separate package.

https://www.npmjs.com/package/prop-types

We should use this going forward, and migrate all old components.

**Comment by mike-robertson** [comment]
Yea, I only did it that way because of conventions I have seen. I don't think there is any significant difference except preference. Encapsulated is probably more readable.

**Comment by howardchung** [comment]
We'll still need to use the assignment style for pure function components, so maybe we should just be consistent and do that everywhere.

**Pull request merged**
