### PR TITLE
Fix item buy time

### LINKED ISSUE #437: Multiple purchases of the same item show wrong timings on overview
https://www.opendota.com/matches/2762021523/overview

Both Daedalus are marked at 26:08. The Purchases tab correctly shows the second one being purchased at 53:02.

### PR DESCRIPTION
**Pull request by pinkiesky**
fixes #437

### CODE REVIEW

**Comment by howardchung** [comment]
Do you have a sample match ID that you tested this against?

**Comment by pinkiesky** [comment]
https://www.opendota.com/matches/2762021523/overview
[Before](https://ibb.co/mYBHJ5) and [with fix](https://ibb.co/dJjRBQ)

**Comment by pinkiesky** [comment]
Fix also affects the buy time of all items in general. 
I think the use of the `purchase_log` is much more reasonable than the `first_purchase_time`.
Is there any reason for use `first_purchase_time`? Perhaps I do not see the whole picture as a whole?

**Comment by howardchung** [comment]
It's just simpler since it doesn't require iterating over the purchase log.

**Pull request merged**
