### PR TITLE
fixes to table scroll. Fixes to counts page in pure css.

### PR DESCRIPTION
**Pull request by mike-robertson**
iphone 5 (320) Table is scrollable at this size:

second 'breakpoint':

full screensize:

### CODE REVIEW

**Comment by mike-robertson** [comment]
@dartharaknus we can achieve the same effect without even needing any media queries or extra code using flexbox properly.

@howardchung

**Comment by howardchung** [comment]
Is this an alternative to #279 ?   LGTM

**Comment by mike-robertson** [comment]
Yes, this would be an alternative

**Comment by dartharaknus** [comment]
I confirmed. This looks good. merge away.

**Pull request merged**
