### PR TITLE
Use valve's color pattern for KDA

### PR DESCRIPTION
**Pull request by dartharaknus**

### CODE REVIEW

**Comment by dartharaknus** [comment]
From Hero Stats in dota game client.

**Comment by howardchung** [comment]
@blukai is this ok with you?

**Comment by blukai** [comment]
I don't think so. Kill - drew blood => red, death - waiting => gray, assist - help => green. This makes some logic. 🦄

**Comment by dartharaknus** [comment]
Not really. Kill => Good for you (green), Death => Bad for you (red). You see a lot of reds on your overview page? Bad for you.

This is the same as valve's color pattern from the "player hero stats" in-game.

**Comment by howardchung** [comment]
Any other input?

@mike-robertson 
@nicholashh 
@albertcui 

I'm fine with it either way.

**Comment by howardchung** [comment]
input from @mike-robertson is that assists should be blue or something other "positive" color.  We can tweak it later.

**Pull request merged**
