### PR TITLE
New translations Simplified Chinese.

### PR DESCRIPTION
**Pull request by kxxoling**
Simplified Chinese translations improved.

### CODE REVIEW

**Comment by howardchung** [comment]
Can you submit this via CrowdIn?  There may be merge issues otherwise.

**Comment by kxxoling** [comment]
I've just uploaded it to CrowdIn.

**Comment by kxxoling** [comment]
BTW, open the translation for TI7 predictions?

**Comment by howardchung** [comment]
Since TI7 predictions is a temporary page I opted not to localize it.  It will be removed after TI7 is over.

**Comment by kxxoling** [comment]
How about adding hero image beside its name? Many non-English speaking players are not familiar with Hero names. But words like "ban", "pick", "hero", "KDA" are easy to understand or find in dict.

**Pull request closed without merging**
