### PR TITLE
Add support for Simplified Chinese

### PR DESCRIPTION
**Pull request by a342191555**

### CODE REVIEW

**Comment by howardchung** [comment]
@albertcui is this the proper way to submit translations?  Do they need to go through crowdin?

**Comment by a342191555** [comment]
@howardchung I am sorry about this, but I have not any experience about the localization work (neither about open-source work). I'd appreciate very much if you can tell me the correct way of submitting translations.

**Comment by howardchung** [comment]
No worries, I'm not sure either.  Albert set up a crowdin project to streamline the process, but you're the first person to do any kind of translation.  Let's see what he says.

http://translate.opendota.com/

**Comment by albertcui** [comment]
Wow, awesome! Our first translator! Thanks for your contribution.

Can you see if you can upload the translations here? http://translate.opendota.com/translate/yasp/6/en-zhcn

We haven't done this before, but I think doing it through Crowdin will allow for review + should automatically push the translations.

**Comment by a342191555** [comment]
@albertcui  I have no permission to upload file. But I've gave all the suggestions. So now I have no idea what to do to tell Crowdin I've finished it.

**Comment by albertcui** [comment]
Thanks! I've merged them through Crowdin.

**Pull request closed without merging**
