### PR TITLE
Moved Ability Build to its own table

### PR DESCRIPTION
**Pull request by jhonnold**
I have moved the ability build to its own table per #1131. 

I made a new table called AbilityBuildTable - following standard layout for that.
I then proceeded to map the array from the ability build into keys in order for it to be used by the prop in the Table.

I had to standardize a couple of values due to how they come from the backend.

I'm not sure if this will cause a performance hit or not - if it does I will have to figure something else out.

Picture with dire scrolled to end:
image

### CODE REVIEW

**Comment by howardchung** [comment]
Could we reduce the padding in order to try to fit all 25 columns without scrolling?

Also I think we can remove the pvgna icon to save some more space, since they're still on the main table.

**Comment by blukai** [comment]
maybe better move **ability builds** to **purchases** tab and call it **builds** instead?

**Comment by jhonnold** [comment]
Okay I'll move it to the purchases and rename that tab to builds and ill reduce padding to get all 25 on the screen for default size

**Comment by coreymaher** [comment]
Ability builds are available without parsing a replay, correct? Doesn't that mean it shouldn't be in a tab that requires a parse?

**Comment by howardchung** [comment]
Yeah, I think we should leave it on the overview tab as it's basic information.

**Comment by jhonnold** [comment]
Alright won't be moving it then

**Comment by jhonnold** [comment]
Here it is after i set a negative margin to shrink padding and lowered the size of the image and removed the pvgna icon

image

**Comment by jhonnold** [comment]
Wait don't pass this in just yet - i just noticed the MK in the screen isn't showing the levels correctly. I'll look into that

**Comment by jhonnold** [comment]
Or not - dotabuff is showing it the same way https://www.dotabuff.com/matches/3360245838

**Comment by howardchung** [comment]
I'll merge this now, @blukai if you have any further comments check the stage version and we can submit any additional fixes before deploying to production?

**Pull request merged**
