### PR TITLE
[ADD] visage-summon-familiars-stone-from image to assets folder

### LINKED ISSUE #1068: "Stone Form" spell icon is throwing a 404 Error
Specifically calls to URL: https://api.opendota.com/apps/dota2/images/abilities/visage_summon_familiars_stone_form_lg.png

Screenshot: https://cdn.discordapp.com/attachments/197560147529170944/336068808764555274/unknown.png

### PR DESCRIPTION
**Pull request by souravmondal93**
fixes #1068 

I added the image as - `assets/images/dota2/neutral-abilities/visage-summon-familiars-stone-form.png`. I have also send a PR to update the dotaconstants repository.

### CODE REVIEW

**Comment by howardchung** [comment]
Run `npm update dotaconstants` and then check the match provided in the issue to see if the issue is fixed.

**Comment by souravmondal93** [comment]
The issue if fixed. I checked it against the links provided in the issue and in few other places. Attaching images for future reference.

Image 1: http://prntscr.com/g2tllp - First link from the issue
Image 2: http://prntscr.com/g2tm2y - Second link from the issue
Image 3: http://prntscr.com/g2tmeg - Other page image

**Comment by howardchung** [comment]
Add the changes to package.json and package-lock.json generated by the update command

**Comment by souravmondal93** [comment]
@howardchung there are no more changes, that I have to commit.

**Comment by howardchung** [comment]
Hmm, that's strange.  Without the changes the UI won't know it needs to use the new dotaconstants.  Are you running npm v5?

**Comment by souravmondal93** [comment]
Node version is 6.11.0. 
The reason it is working because I updated the dotaconstants repository and there is no change required in the package.json file.

In the package.json, it had the following line 

```json
"dependencies": {
    .....
    "dotaconstants": "^5.8.2",
    .....
}
```

which is making it work as the dotaconstants repository as minor version update.

**Comment by howardchung** [comment]
With npm5 the package-lock.json file will cause the dependency tree to use the locked dep tree.

Travis CI build uses the latest node/npm so we have to update package-lock.json as well.

**Comment by souravmondal93** [comment]
How to update package-lock.json automatically?

I have one solution. I will manually update the value to dotaconstants in `package.json` to `5.9.0` then when I will run `npm update dotaconstants` it will update `package-lock.json` as well.

What do you say?

**Comment by souravmondal93** [comment]
Sorry, I didn't notice that you asked about npm version and I replied about node version. I am using npm 3.10.10. Do I need to update npm?

**Comment by howardchung** [comment]
Yes, update to npm5 to get it to update the lockfile for you.

**Comment by souravmondal93** [comment]
I updated my npm and followed the steps that you said. It updated the package-lock.json file. I have pushed my commit and updated the branch as well.

Review it and let me know, if any changes required.

**Comment by howardchung** [comment]
There should also be an update to package.json

**Comment by souravmondal93** [comment]
I am afraid that there was no change in the `package.json` file after running `npm update dotaconstants`. Should I manually update it to `5.9.0`?

**Comment by howardchung** [comment]
Yes, please do

**Comment by souravmondal93** [comment]
I have updated the `package.json` file as well.

**Pull request merged**
