### PR TITLE
Show radiant/dire team name if available

### LINKED ISSUE #538: show radiant/dire team name if available

### PR DESCRIPTION
**Pull request by covertPZ**
fixes #538 

A first pass at making the string modifications. Would like to have some discussion of ways we may want to be passing this data to the `TeamTable` since I feel the way I've implemented may be a bit clunky.
Fix for #538

### CODE REVIEW

**Comment by howardchung** [comment]
@blukai for review

**Comment by howardchung** [comment]
I'm with this approach.  What do you think is clunky about it?

**Comment by covertPZ** [comment]
Mainly the addition of the two props to the `TeamTable` component. We also pass the players value from match into the component, so would we want to just pass the entire match to the component or would that be less efficient/worse practice?

**Comment by howardchung** [comment]
@mike-robertson might want to weigh in.  Originally, TeamTable took the match as input.  It was refactored later to take players only, but now we want additional data from match, so do we want to add new props or go back to passing match?

**Comment by howardchung** [comment]
resolve conflict?

**Comment by covertPZ** [comment]
Sorry, I've been away and haven't been able to get on my dev machine to resolve the conflict. I can update when I return at the beginning of the week.

**Comment by howardchung** [comment]
No worries!  I added you to the org so you can make a branch directly on the repo.  That way it's easier for one of the other contributors to push to your branch for any last-minute cleanup like resolving conflicts.

**Comment by howardchung** [comment]
Actually it looks like GitHub added a UI to support interactive merging directly from the site :)

**Pull request merged**
