### PR TITLE
Creep abilities images - fix Doom casts and damage sources

### LINKED ISSUE #345: creep ability images
Continuation of https://github.com/odota/core/issues/115

dark_troll_warlord_ensnare
ogre_magi_frost_armor
polar_furbolg_ursa_warrior_thunder_clap
centaur_khan_war_stomp
dark_troll_warlord_raise_dead
enraged_wildkin_tornado
satyr_trickster_purge
satyr_soulstealer_mana_burn 
satyr_hellcaller_shockwave
harpy_storm_chain_lightning
keeper_of_the_light_spirit_form_illuminate_end

@dylanking42 found some of the images, but they need to be pushed to github.  It's kind of messy because we typically source the images from valve CDN (proxied through API_HOST for https)

http://imgur.com/a/vgGAQ

### LINKED ISSUE #603: Monkey king ability icons
They are missing currently.

### PR DESCRIPTION
**Pull request by vamo89**
fixes #345 
fixes #603 

About https://github.com/odota/ui/issues/345.
Needs dotaconstants pull request to be accepted before.

### CODE REVIEW

**Comment by vamo89** [comment]
Some matches to see: 2815680709, 2828244110 and 2825159271

**Comment by howardchung** [comment]
I added you to the org so you can merge this yourself when it passes CI

**Comment by howardchung** [comment]
Looks like just unresolved import due to not updated version.  Semver means it'd likely work anyway since 4.5.0 is out now, but you can explicitly bump the version to trigger a new build anyway.

**Comment by vamo89** [comment]
I just retriggered in travis. It should pass now.

**Pull request merged**
