### PR TITLE
Update PlayerThumb to use icon url from dotaconstants

### PR DESCRIPTION
**Pull request by covertPZ**
Updating PlayerThumb for consistency with new reference method for hero icons.

### CODE REVIEW

**Comment by covertPZ** [comment]
Not sure if we also want to remove `getShortHeroName()` all together as this was the only place that it was used in the app and may no longer serve a purpose.

**Comment by howardchung** [comment]
Sure, remove it.

**Comment by howardchung** [comment]
@covertPZ do you want me to merge this now or wait for removal of the unused function?

**Comment by covertPZ** [comment]
@howardchung Sorry, missed your previous reply. I'll remove and push now.

**Pull request merged**
